const products=JSON.parse(localStorage.getItem("cosmo-products")||"null")||[
["Aster Chronograph","Watch",485,12,"Active"],["Élan Automatic","Watch",620,5,"Low stock"],["Noir Date","Watch",395,24,"Active"],["Meridian Classic","Watch",540,8,"Low stock"],["Atlas Sport","Watch",455,16,"Active"],["Luna Minimal","Watch",345,3,"Low stock"],["Regent Automatic","Watch",790,7,"Low stock"],["Signature Leather Strap","Accessory",85,31,"Active"]
];
const orders=[["#CR-1048","Olivia Martin","Aug 16, 2026","$620","Paid"],["#CR-1047","James Carter","Aug 16, 2026","$455","Processing"],["#CR-1046","Sofia Wilson","Aug 15, 2026","$790","Shipped"],["#CR-1045","Daniel Lee","Aug 14, 2026","$345","Paid"],["#CR-1044","Emma Brown","Aug 13, 2026","$540","Delivered"]];
const customers=[["Olivia Martin","olivia@example.com",4,"$1,845","Jun 2026"],["James Carter","james@example.com",2,"$1,075","Jul 2026"],["Sofia Wilson","sofia@example.com",3,"$2,160","May 2026"],["Daniel Lee","daniel@example.com",1,"$345","Aug 2026"],["Emma Brown","emma@example.com",5,"$2,490","Mar 2026"]];
const $=id=>document.getElementById(id);
loginForm.onsubmit=e=>{e.preventDefault();login.classList.add("hidden");app.classList.remove("hidden")};
logout.onclick=()=>{app.classList.add("hidden");login.classList.remove("hidden")};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function showPage(page){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(page).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));pageTitle.textContent=page[0].toUpperCase()+page.slice(1)}
function render(){productsTable.innerHTML=products.map((p,i)=>`<tr><td><strong>${p[0]}</strong></td><td>${p[1]}</td><td>$${p[2].toLocaleString()}</td><td>${p[3]}</td><td><span class="status">${p[4]}</span></td><td><button class="action" onclick="deleteProduct(${i})">Delete</button></td></tr>`).join("");ordersTable.innerHTML=orders.map(o=>`<tr>${o.map((x,i)=>`<td>${i===4?`<span class="status">${x}</span>`:x}</td>`).join("")}</tr>`).join("");customersTable.innerHTML=customers.map(c=>`<tr>${c.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("");recent.innerHTML=orders.slice(0,4).map(o=>`<div class="order"><div><strong>${o[0]}</strong><small>${o[1]} · ${o[2]}</small></div><strong>${o[3]}</strong></div>`).join("");chart.innerHTML=[["Feb",38],["Mar",51],["Apr",43],["May",67],["Jun",59],["Jul",82],["Aug",96]].map(x=>`<div class="bar" style="height:${x[1]}%"><span>${x[0]}</span></div>`).join("")}
function deleteProduct(i){if(confirm("Delete this product?")){products.splice(i,1);localStorage.setItem("cosmo-products",JSON.stringify(products));render()}}
addProduct.onclick=()=>modal.classList.remove("hidden");function closeModal(){modal.classList.add("hidden")}
productForm.onsubmit=e=>{e.preventDefault();products.push([pname.value,pcat.value,Number(pprice.value),Number(pstock.value),Number(pstock.value)<10?"Low stock":"Active"]);localStorage.setItem("cosmo-products",JSON.stringify(products));render();closeModal();productForm.reset()}
render();
