const express=require('express');
const multer=require('multer');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');

const app=express();
const PORT=process.env.PORT||3000;
const ROOT=__dirname;
const DATA=path.join(ROOT,'data');
const UPLOADS=path.join(ROOT,'uploads');
fs.mkdirSync(DATA,{recursive:true}); fs.mkdirSync(UPLOADS,{recursive:true});
const productsFile=path.join(DATA,'products.json'); const ordersFile=path.join(DATA,'orders.json');
const readJson=(file,fallback)=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}};
const writeJson=(file,data)=>fs.writeFileSync(file,JSON.stringify(data,null,2));
let products=readJson(productsFile,[]); let orders=readJson(ordersFile,[]);
const sessions=new Map();
const upload=multer({storage:multer.diskStorage({destination:UPLOADS,filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(null,crypto.randomBytes(10).toString('hex')+ext)}}),limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});
app.use(express.json()); app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(UPLOADS)); app.use(express.static(path.join(ROOT,'public')));
function auth(req,res,next){const token=req.headers.authorization?.replace('Bearer ','')||req.cookies?.cosmo_admin; if(token&&sessions.has(token)){req.admin=true;return next()} return res.status(401).json({error:'Unauthorized'});}
app.get('/api/config',(req,res)=>res.json({brand:'Cosmorolex Watches',email:'sales@cosmorolex.com',address:'4009 Hillsboro Pike, Nashville, TN 37215',crypto:{asset:process.env.CRYPTO_ASSET||'USDC',network:process.env.CRYPTO_NETWORK||'Ethereum',wallet:process.env.CRYPTO_WALLET_ADDRESS||''}}));
app.get('/api/products',(req,res)=>{const q=(req.query.q||'').toLowerCase();const category=req.query.category;let out=products.filter(p=>(!q||[p.name,p.brand,p.category,p.description].join(' ').toLowerCase().includes(q))&&(!category||p.category===category));res.json(out)});
app.post('/api/admin/login',(req,res)=>{const user=req.body.user,password=req.body.password;const expectedUser=process.env.ADMIN_USER||'admin',expectedPass=process.env.ADMIN_PASSWORD||'change-this-password';if(user!==expectedUser||password!==expectedPass)return res.status(401).json({error:'Invalid credentials'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,Date.now()+8*60*60*1000);res.json({token})});
app.post('/api/admin/logout',auth,(req,res)=>{const token=req.headers.authorization?.replace('Bearer ','');if(token)sessions.delete(token);res.json({ok:true})});
app.post('/api/admin/products',auth,upload.array('images',8),(req,res)=>{try{const p={id:crypto.randomUUID(),name:req.body.name,brand:req.body.brand||'Cosmorolex',category:req.body.category||'Watches',price:Number(req.body.price||0),currency:'USD',description:req.body.description||'',ref:req.body.ref||'',stock:Number(req.body.stock||1),featured:req.body.featured==='true',images:(req.files||[]).map(f=>'/uploads/'+f.filename)};if(!p.name||!Number.isFinite(p.price))return res.status(400).json({error:'Name and valid price required'});products.unshift(p);writeJson(productsFile,products);res.json(p)}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/products/:id',auth,upload.array('images',8),(req,res)=>{try{const p=products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});Object.assign(p,{name:req.body.name||p.name,brand:req.body.brand||p.brand,category:req.body.category||p.category,price:req.body.price!==undefined?Number(req.body.price):p.price,description:req.body.description??p.description,ref:req.body.ref??p.ref,stock:req.body.stock!==undefined?Number(req.body.stock):p.stock,featured:req.body.featured!==undefined?req.body.featured==='true':p.featured});if(req.files?.length)p.images=(p.images||[]).concat(req.files.map(f=>'/uploads/'+f.filename));writeJson(productsFile,products);res.json(p)}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/admin/products/:id',auth,(req,res)=>{const p=products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});for(const img of p.images||[]) {const f=path.join(ROOT,img.replace(/^\//,'')); if(fs.existsSync(f))fs.unlinkSync(f)}products=products.filter(x=>x.id!==p.id);writeJson(productsFile,products);res.json({ok:true})});
app.post('/api/orders',(req,res)=>{const {customer,items,paymentMethod}=req.body;if(!customer?.name||!customer?.email||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Missing order details'});const full=items.map(i=>{const p=products.find(x=>x.id===i.id);return p?{id:p.id,name:p.name,price:p.price,qty:Math.max(1,Math.min(20,Number(i.qty)||1))}:null}).filter(Boolean);if(!full.length)return res.status(400).json({error:'No valid products'});const total=full.reduce((s,i)=>s+i.price*i.qty,0);const order={id:'CR-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),customer,paymentMethod:paymentMethod||'crypto',items:full,total,currency:'USD',status:'pending'};orders.unshift(order);writeJson(ordersFile,orders);res.json({order,crypto:{asset:process.env.CRYPTO_ASSET||'USDC',network:process.env.CRYPTO_NETWORK||'Ethereum',wallet:process.env.CRYPTO_WALLET_ADDRESS||'',instructions:'Send only the configured asset on the configured network. The order remains pending until payment is verified.'}})});
app.get('/api/admin/orders',auth,(req,res)=>res.json(orders));
app.get('/admin',(req,res)=>res.sendFile(path.join(ROOT,'public/admin/index.html')));
app.listen(PORT,()=>console.log(`Cosmorolex running at http://localhost:${PORT}`));
